name: Build and Deploy Sphinx Site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sphinxdoc/sphinx

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install myst-nb
          pip install pydata-sphinx-theme

      - name: Make static files
        run: make html

      - name: Package and upload artifact of static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy uploaded artifact to GitHub Pages
        uses: actions/deploy-pages@v4
